[package]
name = "bevy_fps_controller"
version = "0.2.4"
edition = "2021"
authors = ["bevy_fps_controller"]
repository = "https://github.com/qhdwight/bevy_fps_controller"
categories = ["game-engines"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Bevy plugin that adds a Source engine inspired FPS movement controller"

[dependencies]
bevy = "0.12.1"
bevy_rapier3d = "0.23.0"
bevy_renet = { version = "0.0.10", optional = true }

[features]
default = []
renet = ["bevy_renet"]

[[example]]
name = "minimal"
path = "examples/minimal.rs"
